### ISSUE TITLE
Images should inherit from base-notebook

### ISSUE THREAD

**Issue by yuvipanda** [pangeo-data/pangeo-stacks#31]
Currently pangeo-notebook image isn't based on the base-notebook image. Ideally, it would be - and we can put things every image must have (what is currently in the appendix) into the base-notebook. It'd also remove duplication in environment.yml, etc.

**Comment by jhamman** [comment]
I'm 100% in favor of this. Not being able to share the appendix between images makes the current approach pretty tough to manage.

**Comment by yuvipanda** [comment]
Should be easy to do once #27 lands. All images can simply use the base-notebook-onbuild version as their base!

**Comment by jhamman** [comment]
closed by #32

**Comment by yuvipanda** [comment]
This is done with #32

**Comment by jhamman** [comment]
![image](https://user-images.githubusercontent.com/2443309/56435007-c06f3300-628b-11e9-92d4-8e11ac6743e6.png)

@yuvipanda - Good to see we're on the same page!

**Comment by yuvipanda** [comment]
@jhamman haha, literally in this case.
