### ISSUE TITLE
where does onbuild put the repo contents

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-stacks#40]
In the new docs (#39), @yuvipanda wrote

> The contents of your directory are copied with appropriate permissions into the image

But **where** are they copied. In the old setup, I could find the repo contents in `/srv/repo`. Now I don't know any more.

This is related to https://github.com/pangeo-data/pangeo-cloud-federation/issues/148

I am trying to add a dask configuration file, but I don't know where to put it.

**Comment by yuvipanda** [comment]
It copies them into ${REPO_DIR}, which could expand to either ${HOME} or /srv/repo depending on how it is set up.

https://github.com/pangeo-data/pangeo-cloud-federation/pull/258 is however the 'right' thing to do for dask config.
