### ISSUE TITLE
stick to conda-forge packages?

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-stacks#42]
Cross posting this issue from pangeo-cloud-federation since it is relevant here:
https://github.com/pangeo-data/pangeo-cloud-federation/issues/254 

In particular, the base image is mixing conda-forge and pip:
https://github.com/pangeo-data/pangeo-stacks/blob/master/base-notebook/binder/environment.yml

But then pangeo-notebook installs some of the same stuff via conda-forge:
https://github.com/pangeo-data/pangeo-stacks/blob/master/pangeo-notebook/binder/environment.yml

I think this is leading to 'inconsistent environment' messages in the hub. @rabernat and @jhamman , could you take a look at the linked issue? I'm wondering if it might be good to:

1) use just conda-forge
2) unpin version numbers (since the docker builds by date effectively save references to compatible package combinations)

**Comment by jhamman** [comment]
I'd be fine with us standardizing on conda-forge and unpinning the version numbers. I also just updated the repo2docker version used here which also gives us a more recent version of conda.
