### ISSUE TITLE
Should I worry about "apt-utils is not installed"?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-stacks#52]
When I building locally, I see message like:
```
debconf: delaying package configuration, since apt-utils is not installed
```
Is that anything to worry about?

**Comment by jhamman** [comment]
I don't think there is anything to worry about here. This is something that comes from repo2docker so unless we see some problems that we can attribute to this warning, I think we can consider it innocuous for now.
