### ISSUE TITLE
version badge doesn't automatically update

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-stacks#56]
The microbadger buttons in the repo readme.md are pretty cool, but don't seem to update automatically:

[![](https://images.microbadger.com/badges/version/pangeo/base-notebook.svg)](https://microbadger.com/images/pangeo/base-notebook "Get your own version badge on microbadger.com")

Is there some magic we can implement so that this updates when we push new images to dockerhub? The latest is 2019.07.01 (https://hub.docker.com/r/pangeo/base-notebook/tags)

@jhamman

**Comment by jhamman** [comment]
I think we were missing the microbadger webhook integration. I've just added it so hopefully it will update on the next tag.
