### ISSUE TITLE
Addition of   dask-gateway causes dependency panic

### ISSUE THREAD

**Issue by scollis** [pangeo-data/pangeo-stacks#73]
When using the latest base-notebook with This env:
https://github.com/scollis/binderhack/blob/master/binder/environment.yml
I get (after a glacial wait)

```
UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (pip):

  - boto -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
  - boto3 -> s3transfer[version='>=0.1.10,<0.2.0,>=0.2.0,<0.3.0'] -> botocore[version='>=1.12.36,<2.0.0,>=1.3.0,<2.0.0'] -> urllib3[version='>=1.20,<1.24,>=1.20,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.9,>=2.2.1'] -> cffi[version='>=1.7'] -> pycparser -> python[version='3.6.*,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
```

I built a new docker image without dask-gateway and I have no issues building an image on top of that using repo2docker with it as the base Docker

**Comment by TomAugspurger** [comment]
It appears that conda-forge is only building dask-gateway packages for 3.7, while the pangeo-stacks is on 3.6

@jcrist do you know why only 3.7 is built? (I think Jim is out on vacation for a week or so. I can try taking a look early next week).

**Comment by jcrist** [comment]
Apologies about this. Version `0.2.0` was accidentally incompatible, and I forgot to update the conda-forge recipe for version `0.3.0` (long since released) which remedied this. All fixed now, you should be able to install `dask-gateway` from conda-forge on `python >= 3.6`.

**Comment by jhamman** [comment]
Thanks @jcrist!
