### ISSUE TITLE
Updating dask

### ISSUE THREAD

**Issue by stb2145** [pangeo-data/pangeo-stacks#77]
Opening an issue to bring to attention that we should update dask to its newest version 2.4.0.

**Comment by jhamman** [comment]
Hi @stb2145 - absolutely. Xarray also just issued a new release. Can I ask you to open a PR to bump a few versions?

Dask version is here:
https://github.com/pangeo-data/pangeo-stacks/blob/ae634bf963bc07f043fa8899e84d124b32146ade/base-notebook/binder/environment.yml#L9

Xarray version is here:
https://github.com/pangeo-data/pangeo-stacks/blob/ae634bf963bc07f043fa8899e84d124b32146ade/pangeo-notebook/binder/environment.yml#L10

It would also be good to add `sparse >= 0.8` to pangeo-notebook.

**Comment by rabernat** [comment]
Should be be bumping up to dask 0.2.4 and xarray 0.13.0?

**Comment by stb2145** [comment]
Under which dependency category should I add `sparse>=0.8`?

**Comment by jhamman** [comment]
closed via #80
